### ISSUE TITLE
Question: how to run dorylus on other platforms

### ISSUE THREAD

**Issue by CodingYuanLiu** [uclasystem/dorylus#2]
Dear maintainers,

I'm using another faas platform rather than AWS Lambda and I would like to run dorylus on other serverless platforms like openwhisk. However, I find that the implementation of dorylus is tightly coupled with AWS Lambda.

Could you please give me some advice on how to run dorylus on other platforms? 
E.g., what files should I modify? How much time or effort I need to take approximately?

Thank you!

**Comment by johnnt849** [comment]
Hi,

You're right that our current implementation assumes that the serverless implementation will be AWS Lambda. However, it should be possible to implement a module specific to OW so that you can run your own serverless threads.

You can implement a new `ResourceComm` module as seen in [`src/graph-server/resource_comm.hpp`](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/commmanager/resource_comm.hpp) which is a virtual class that can implement different backends. You can follow our example of [`src/graph-server/lambda_comm.hpp`](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/commmanager/lambda_comm.hpp) which starts by initializing several listener threads ([`LambdaWorker`](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/commmanager/lambdaworker.hpp#L37)) and then uses the [`NNCompute()`](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/commmanager/lambda_comm.cpp#L49) function to invoke Lambdas. Basically you should take our similar logic from [`src/graph-server/lambda_comm.cpp`](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/commmanager/lambda_comm.cpp) such as [`LambdaComm::invokeLambda()`](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/commmanager/lambda_comm.cpp#L141), [`LambdaComm::asyncRelaunchLoop()`](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/commmanager/lambda_comm.cpp#L90), and [`LambdaComm::callback()`](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/commmanager/lambda_comm.cpp#L172). The rest of the implementation should be reusable. The [`LambdaWorker`](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/commmanager/lambdaworker.hpp#L37) class for example is not tied to AWS Lambdas, it just listens for requests and sends/receives tensors.

You will also need to add some logic to instantiate the new `ResourceComm` class [here](https://github.com/uclasystem/dorylus/blob/bdd672f807e5bc5f953bbf97de802c095d9293ff/src/graph-server/engine/engine.cpp#L151).

As long as you have some way of invoking your serverless functions and have it compiled and uploaded to your serverless platform then that should work. I would estimate this taking about 2 to 3 weeks.

**Comment by CodingYuanLiu** [comment]
Thank you very much! Your answer is really helpful.
